### ISSUE TITLE
is there plan to update this repo to have more support on the testobject api?

### ISSUE THREAD

**Issue by waynemd** [saucelabs/testobject-appium-ruby-api#3]
Hi,
I see more support on the https://github.com/saucelabs/testobject-java-api for the testobject api?  is there any more update on the ruby side?

Thanks

**Comment by christian-bromann** [comment]
Hey @waynemd 👋 

We will continue developing our API bindings for Ruby in here: https://github.com/saucelabs/sauce_whisk. For Java we recommend to check out https://github.com/saucelabs/saucerest-java and for Node.js we maintain https://github.com/saucelabs/node-saucelabs.

Cheers!
